### ISSUE TITLE
Upload Functionality?

### ISSUE THREAD

**Issue by connor4312** [aidewoode/black_candy#7]
First of all, awesome work on this project! I've been working on getting a relative digitized after some hardware failures and this is just the thing for the music side of that.

I've now got this running on an Azure VM. It'd be great if there was a way for non-technical users to upload songs to black_candy. For the moment I'm just ripping CDs and `rsync`'ing them up, but I'd rather not be the sole arbiter of this process going forward :)

**Comment by aidewoode** [comment]
You are right, it's not convenient for some users. They should upload files manually. I will do some work  to make upload files easier. Thank you.

**Comment by zeigerpuppy** [comment]
Rather than re-inventing upload functionality, perhaps it's worth checking out web-based file management programs.

One of my favourites is [Filestash](https://github.com/mickael-kerjean/filestash).  It supports multiple formats (FTP, SCP, WebDAV, etc...) and is easy to run in a docker container.  It should be possible to reskin it a bit and per-configure using docker-compose to integrate it fairly easily.

**Comment by aidewoode** [comment]
Yes，Instead of developing an upload feature, it would be better to let the user choose what method to use to upload the audio file. Because there are quite lot solutions available.

**Comment by KaoruDev** [comment]
What about reading from a cloud bucket?

**Comment by aidewoode** [comment]
I think support object storage is a good idea, but the object storage  must with serverless support. Right now I just know Amazon S3 with Lambda and Cloudflare R2 with Workers support this. Because we need read meta data from audio file, but we can't read whole file from object storage service just for meta data, it's inefficient and slow.  With  serverless  support, we can use serverless  code to read file meta data when file is uploaded on object storage service. Cloudflare R2 is a good alternative for S3  and cheaper than S3, so  I will chose to support Cloudflare R2 as media library when R2 is released.

**Comment by sergiustheblack** [comment]
The same approach (read once on upload, send metadata, use metadata from Database) was implemented in earlier version of Koel. As for me it was quite convenient to use with AWS Lambda-like functions.
